name: new_features
description: New Features
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
    
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  intl: ^0.19.0
  unicons: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2

flutter:
  uses-material-design: true
